services:
  - type: web
    name: text-rephraser-frontend
    env: static
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production 